# Generated by Django 2.2.7 on 2019-11-26 00:21

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accionista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago_dividendo',
            fields=[
                ('pago_id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField()),
                ('Estado_pago', models.CharField(choices=[('APROBADO', 'Aprobado'), ('PENDIENTE', 'Pendiente'), ('RECHAZADO', 'Rechazado')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('accionista_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accionista.Accionista')),
            ],
            managers=[
                ('pago', django.db.models.manager.Manager()),
            ],
        ),
    ]
