# Generated by Django 2.2.7 on 2019-11-26 03:17

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accionista',
            fields=[
                ('accionista_id', models.AutoField(primary_key=True, serialize=False)),
                ('run', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(default='', max_length=100)),
                ('apellidos', models.CharField(default='', max_length=100)),
                ('nacionalidad', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('telefono', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('email', models.CharField(blank=True, default='example@correo.com', max_length=100, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('firma', models.ImageField(blank=True, null=True, upload_to='accionistas')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            managers=[
                ('accionistas', django.db.models.manager.Manager()),
            ],
        ),
    ]
