# Generated by Django 2.2.5 on 2019-09-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accionista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accionista',
            name='imagen',
            field=models.ImageField(null=True, upload_to='accionistas'),
        ),
    ]
