# Generated by Django 2.2.5 on 2019-09-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accionista', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accionista',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='accionistas'),
        ),
    ]
