# Generated by Django 2.2.5 on 2019-09-13 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accionista', '0002_accionista_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accionista',
            name='imagen',
            field=models.FileField(null=True, upload_to='accionistas'),
        ),
    ]
