# Generated by Django 2.2.7 on 2019-11-26 01:47

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accionista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('tercero_id', models.AutoField(primary_key=True, serialize=False)),
                ('run', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('apoderado', 'APODERADO'), ('corredor', 'CORREDOR'), ('representante', 'REPRESENTANTE')], default='', max_length=200)),
                ('poder', models.BooleanField()),
                ('firma', models.ImageField(blank=True, null=True, upload_to='terceros')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('accionista_id', models.ManyToManyField(to='accionista.Accionista')),
            ],
            managers=[
                ('terceros', django.db.models.manager.Manager()),
            ],
        ),
    ]
