# Generated by Django 2.2.5 on 2019-09-30 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tercero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='accionista_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accionista.Accionista'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='apellidos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='nombres',
            field=models.CharField(max_length=100),
        ),
    ]
