# Generated by Django 2.2.2 on 2019-06-24 19:05

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accionista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('run', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('totalAcciones', models.IntegerField()),
                ('nacionalidad', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=40)),
                ('fecha_Nacimiento', models.DateField()),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('fax', models.IntegerField()),
            ],
            managers=[
                ('accionistas', django.db.models.manager.Manager()),
            ],
        ),
    ]
