# Generated by Django 2.2.2 on 2019-06-25 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accionista', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accionista',
            name='fecha_Nacimiento',
        ),
        migrations.RemoveField(
            model_name='accionista',
            name='id',
        ),
        migrations.AlterField(
            model_name='accionista',
            name='run',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
