# Generated by Django 2.2.2 on 2019-06-25 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accionista', '0002_auto_20190624_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accionista',
            name='apellido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='accionista',
            name='direccion',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='accionista',
            name='email',
            field=models.CharField(default='example@correo.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='accionista',
            name='fax',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accionista',
            name='nacionalidad',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accionista',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='accionista',
            name='telefono',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accionista',
            name='totalAcciones',
            field=models.IntegerField(default=0),
        ),
    ]
